version: '3'
services:

  kafka:
    container_name: jdbc-kafka
    image: quay.io/strimzi/kafka:latest-kafka-3.4.0
    command: [
      "sh", "-c",
      "export CLUSTER_ID=$$(bin/kafka-storage.sh random-uuid) && bin/kafka-storage.sh format -t $$CLUSTER_ID -c config/kraft/server.properties && bin/kafka-server-start.sh config/kraft/server.properties --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override listener.security.protocol.map=$${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP} --override listeners=$${KAFKA_LISTENERS}"
    ]
    ports:
      - "29092:29092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092

  mysql:
    container_name: jdbc-mysql
    image: quay.io/debezium/example-mysql:2.3
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=dbz
      - TZ=Europe/Vienna
    command:
      ./entrypoint.sh --default-time-zone="SYSTEM"

  postgres:
    container_name: jdbc-postgres
    image: quay.io/debezium/example-postgres:2.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=dbz
      - TZ=Europe/Vienna
      - PGTZ=Europe/Vienna

  connect:
    container_name: jdbc-connect
    image: quay.io/debezium/connect:2.3
    ports:
      - "8083:8083"
    links:
      - kafka
      - mysql
      - postgres
    depends_on:
      - kafka
      - mysql
      - postgres
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=connect_configs
      - OFFSET_STORAGE_TOPIC=connect_offsets
      - STATUS_STORAGE_TOPIC=connect_statuses